name: ai-test-generator

version: "3.7"

services:
  api:
    container_name: ai-test-generator-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ai_test_generator_runtime:/app/data/runtime
      - gi20_secrets_container:/run/secrets:ro
    networks:
      - gi20backendnetwork-prod

networks:
  gi20backendnetwork-prod:
    name: gi20network
    external: true
    driver: bridge

volumes:
  ai_test_generator_runtime:
    name: ai_test_generator_runtime
  gi20_secrets_container:
    external: true
    name: gi-20-backend_gi20_secrets_container
