"""Multiple-choice question counts — shared by models, prompts, and helpers (avoid import cycles)."""

MC_QUESTION_OPTION_COUNT_MIN = 2
MC_QUESTION_OPTION_COUNT_MAX = 6
MC_QUESTION_OPTION_COUNT_DEFAULT = 4
MC_QUESTION_CORRECT_INDICES_MIN_COUNT = 1
MC_QUESTION_EXPLANATION_SOFT_MAX_CHARS = 1000
